---
- name: Run tests
  hosts: all

  # become: true
  any_errors_fatal: true

  vars:
    # Variables defined by command line.
    # database: "postgres"
    # benchmark: "tpcc"

    # Local paths.
    configs_folder: "{{ playbook_dir }}/configs/{{ database }}/{{ benchmark }}/*.xml"

    # Remote paths.
    benchmark_folder: "/home/gsd/geo-c-java"

  tasks:
    - name: Create config folder if it does not exist
      ansible.builtin.file:
        path: "{{ benchmark_folder }}/configs"
        state: directory

    - name: Copy local config files to remote
      ansible.builtin.copy:
        src: "{{ item }}"
        dest: "{{ benchmark_folder }}/configs/{{ item | basename }}"
        owner: gsd
      with_fileglob: "{{ configs_folder }}"

    - name: Read the names of all config files
      ansible.builtin.find:
        paths: "{{ benchmark_folder }}/configs"
      register: configs

    - name: Run benchmark for all configs
      ansible.builtin.shell: |
        ./mvnw clean compile exec:java -P {{ database }} \
          -Dexec.args="-d results/{{ database }}/{{ benchmark }}/{{ item.path | basename | splitext | first }} -b {{ benchmark }} -c {{ item.path }} --create=true --load=true --execute=true"
      args:
        chdir: "{{ benchmark_folder }}"
      loop: "{{ configs.files }}"

    - name: Fetch results
      ansible.posix.synchronize:
        src: "{{ benchmark_folder }}/results"
        dest: remote_results
        mode: pull
