# -*- mode: ruby -*-
# vi: set ft=ruby :

# Select here the desired deployment preset.
PRESET = :cockroachdb_single

settings = case PRESET
  when :cockroachdb_single then { number: 1, type: :cockroachdb }
  when :cockroachdb_triple then { number: 3, type: :cockroachdb }
  when :postgres then { number: 1, type: :postgres }
  else raise 'Invalid preset! Pick another one.'
end

Vagrant.configure('2') do |config|
  # For a complete reference, please see the online documentation at
  # https://docs.vagrantup.com.

  config.vm.box = 'bento/ubuntu-22.04'

  # Uncomment if the machine takes too long to boot.
  # config.vm.boot_timeout = 3000

  # Create a private network, which allows host-only access to the machine
  # using a specific IP.
  # config.vm.network "private_network", ip: "192.168.33.10"

  case settings[:type] 
    when :postgres then
      config.vm.network 'forwarded_port', guest: 5432, host: 5432 
    when :cockroachdb then
      config.vm.network 'forwarded_port', guest: 26257, host: 26257 
  end

  config.vm.provider 'virtualbox' do |vb|
    vb.memory = '512'
  end

  config.vm.provision 'ansible' do |ansible|
    ansible.verbose = 'v'
    ansible.playbook = 'ansible/playbook.yml'
  end

  (1..settings[:number]).each do |i|
    config.vm.define "#{settings[:type]}#{i}" do |node|
      node.vm.hostname = "#{settings[:type]}#{i}"
      # node.vm.network :private_network, ip: "10.0.0.#{2+i}"
    end
  end
end
