---
- name: Setup OS
  hosts: all
  become: true
  roles:
    - common

- name: Install PostgreSQL
  hosts: postgres
  become: true
  roles:
    - postgres

- name: Install CockroachDB
  hosts: cockroachdb
  become: true
  roles:
    - cockroach