---
- name: Setup OS
  hosts: "*"
  become: true
  roles:
    - common

- name: Install PostgreSQL
  hosts: "*"
  become: true
  roles:
    - postgres

- name: Install CockroachDB
  hosts: "*"
  become: true
  roles:
    - cockroach
