---
- name: Setup OS
  hosts: all
  become: true
  roles:
    - common

- name: Install PostgreSQL
  hosts: postgres
  become: true
  roles:
    - postgres

- name: Install CockroachDB
  hosts: cockroachdb
  become: true
  roles:
    - cockroach

- name: Initialize CockroachDB cluster
  hosts: cockroachdb1
  become: true
  any_errors_fatal: true
  tasks:
    - name: Initialize cluster and database (only on the first node)
      ansible.builtin.shell: |
        cockroach init --insecure --host=localhost:26257
        cockroach sql --execute="CREATE DATABASE benchbase;" --insecure --host=localhost:26257
      ignore_errors: true

- name: Deploy proxy for CockroachDB
  hosts: haproxy
  become: true
  roles:
    - cockroach_proxy